version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb_container
    environment:
      MYSQL_ROOT_PASSWORD: passwd
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"
